# Generated by Django 5.2 on 2025-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_address_order_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moon_points_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
