# Generated by Django 5.2 on 2025-05-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_lunar_powered_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sustainability_score',
            field=models.PositiveIntegerField(default=0, help_text='Score from 1-100 showing environmental impact'),
        ),
    ]
