# Generated by Django 5.2 on 2025-05-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_sustainability_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sustainability_score',
            new_name='lunar_score',
        ),
    ]
