# Generated by Django 5.2 on 2025-05-10 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_sustainability_score_product_lunar_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cosmic_effects',
            field=models.JSONField(default=list, help_text='A list of fun, cosmic effects this product allegedly has.'),
        ),
    ]
