# Generated by Django 5.2 on 2025-05-09 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash_on_delivery', 'Cash On Delivery')], max_length=20),
        ),
    ]
