# Generated by Django 5.2 on 2025-05-09 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_address_customuser_avatar_customuser_bio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='last_sun_point_claim',
            new_name='last_moon_point_claim',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='sun_points',
            new_name='moon_points',
        ),
    ]
